### ISSUE TITLE
Divisores primos

### ISSUE THREAD

**Issue by hinojosaad** [MacMotx/nuwe_coding_exercise2#1]
Hola, una sugerencia para mejorar tu código: un divisor primo es a lo más la raíz cuadrada del número, no es necesario que revises todos!
https://www.youtube.com/watch?v=9iH8mY3iGLk

**Comment by EliesLP** [comment]
Ey Adrian! Como estas? Muchas gracias por el tip 😉(ahora entiendo porque se quedaba pensando 😅) ya lo arreglé.

Muy instructivo el video, merci

Un saludo 🤗, a ver si podemos coincidir en algun hackathon.

**Comment by hinojosaad** [comment]
De nada saludos, ojalá y coincidamos pronto!
